# -*- coding: utf-8 -*-
"""Calculadora Efecto Multiplicador Monetario.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NaSL0W3AG0EURL2kDCgjfccDPn6SJ5ZG

# CALCULADORA EFECTO MULTIPLICADOR MONETARIO
El efecto multiplicador monetario indica cómo la base monetaria (dinero creado por el banco central) se multiplica para generar la oferta monetaria total en la economía.

La fórmula es:

𝑀
=
(
𝑒
+
1
𝑒
+
𝑟
)
⋅
𝐵
M=(
e+r
e+1
​
 )⋅B
donde:

𝑀
M: Oferta monetaria total

𝐵
B: Base monetaria

𝑒
=
𝐸
𝐷
e=
D
E
​
 : Proporción de efectivo en poder del público respecto a los depósitos

𝑟
=
𝑅
𝐷
r=
D
R
​
 : Proporción de reservas bancarias respecto a los depósitos

𝐸
E: Efectivo en poder del público

𝑅
R: Reservas bancarias

𝐷
D: Depósitos bancarios

Condiciones importantes:

Los depósitos
𝐷
D no pueden ser cero

𝑒
e debe ser mayor o igual a cero

𝑟
r debe estar entre 0 (exclusivo) y 1 (inclusive)

Esta fórmula muestra cómo la cantidad total de dinero
𝑀
M depende no solo de la base monetaria
𝐵
B, sino también de los comportamientos del público y los bancos en cuanto a efectivo y reservas.
"""

# Librerías necesarias
import ipywidgets as widgets
from IPython.display import display, clear_output, Markdown, Latex, HTML

# Título
display(HTML("<h1 style='text-align:center; color:darkblue;'>Calculadora Efecto Multiplicador Monetario</h1>"))


display(HTML("<hr>"))
display(Markdown("### Ingresá los valores:"))

# Widgets de entrada
R_widget = widgets.FloatText(description="Reservas R:", step=0.1, layout=widgets.Layout(width='300px'))
E_widget = widgets.FloatText(description="Efectivo E:", step=0.1, layout=widgets.Layout(width='300px'))
D_widget = widgets.FloatText(description="Depósitos D:", step=0.1, layout=widgets.Layout(width='300px'))
B_widget = widgets.FloatText(description="Base B:", step=0.1, layout=widgets.Layout(width='300px'))

button = widgets.Button(description="Calcular M", button_style='success')
output = widgets.Output()

def calcular_M(R, E, D, B):
    if D == 0:
        return "❌ Error: D no puede ser 0.", None, None
    e = E / D
    r = R / D
    if e < 0:
        return "❌ Error: e debe ser mayor o igual a 0 (E/D ≥ 0).", None, None
    if not (0 < r <= 1):
        return "❌ Error: r debe estar entre 0 (exclusivo) y 1 (inclusivo).", None, None
    M = ((e + 1) / (e + r)) * B
    return f"✅ Resultado: M = {M:.4f}", e, r

def on_button_click(b):
    with output:
        clear_output()
        R = R_widget.value
        E = E_widget.value
        D = D_widget.value
        B = B_widget.value
        resultado, e, r = calcular_M(R, E, D, B)
        print(resultado)
        if e is not None and r is not None:
            print(f"Coeficiente e = E/D = {e:.4f}")
            print(f"Coeficiente r = R/D = {r:.4f}")

button.on_click(on_button_click)

form = widgets.VBox([R_widget, E_widget, D_widget, B_widget, button, output])
display(form)